### ISSUE TITLE
Specifying dbt_tags__database and dbt_tags__schema does not work as expected

### ISSUE THREAD

**Issue by bkimjin** [infinitelambda/dbt-tags#19]
### Describe the bug
In version 1.2.0, specifying `dbt_tags__database` and `dbt_tags__schema` uses the dbt generated schema and database names instead of the actual values from the variables. 

### Steps to reproduce
Set the variables differently from the actual database and schema in the `profiles.yml`:
```
vars:
  dbt_tags__database: prod
  dbt_tags__schema: public
```

profiles.yml:
```
my_project:
  outputs:
    dev:
      schema: bkim2jin
      database: dev

```

### Expected results
Tag location is in `prod.public`.

### Actual results
Tag location is in `dev.bkim2jin_public`.

### System information

**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**

- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**

```log
dbt core: 1.8.7
snowflake: 1.8.4
```

### Additional context
`get_resource_ns.sql`, line 7.

### Are you interested in contributing the fix?
Yes, fix incoming.

**Comment by il-dat** [comment]
Hi @bkimjin Thanks for raising the issue and the PR too!

Actually this is the intentional behavior of `dbt-tags` following the dbt default one: schema name will be prefixed with the profile schema if there is no overriding logic done in `generate_schema_name` macro.

This is very crucial feature to support the env management, distinguishing between dev vs prod, or dev-person1 vs dev-person2.

I also understand your finding here, so might I suggest to change it to be an enhancement? As I am thinking, we might add a new flag called `dbt_tags__opt_in_default_naming_config` (or similar), True by default, and then we can turn it to False to follow your suggestion.

Let me know what you think!
Cheers

**Comment by bkimjin** [comment]
@il-dat thanks for letting me know! That's the route I initially took, but after reviewing the installation video and reading some of the comments, I made the incorrect assumption that it wasn't working as expected.

I'll go ahead and update it with the variable you mentioned. Do you want me to keep the scope as is, or should I expand this scope to touch on the other macros?

**Comment by il-dat** [comment]
Thanks @bkimjin 

Yes please go ahead and the scope should be only in `get_resource_ns` macro which is the centralized place to calculate the namespace for all the objects of this package by default.

For my demo, sorry for the confusing, it might be worth an update of docs site somewhere to indicate it.

**Comment by bkimjin** [comment]
Regarding the docs site, is that something you wanted me to do? Otherwise, the PR is ready for review.

**Comment by il-dat** [comment]
Thanks @bkimjin Merged and deployed ✅ 

I've also updated the docs site for it too, please refer to https://dbt-tags.iflambda.com/latest/getting-started.html#1-configure-the-namespace-databse-schema

Cheers
